# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geli.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(814, 617)
        Form.setStyleSheet("background-color: #e0f7fa")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(190, 30, 411, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(260, 80, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(140, 80, 121, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(380, 80, 75, 23))
        self.pushButton.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(30, 140, 751, 441))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 590, 791, 20))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 741, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "文件隔离区"))
        self.label_4.setText(_translate("Form", "安全警告：这里的文件都可能带有威胁，请小心进行操作！"))
        self.label_5.setText(_translate("Form", "请输入文件编号："))
        self.pushButton.setText(_translate("Form", "恢复文件"))
        self.label_2.setText(_translate("Form", "提示：可以输入[文件编号]-[文件编号]批量恢复文件"))
