# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(813, 613)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form.setFont(font)
        Form.setStyleSheet("background-color: #e0f7fa")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 50, 591, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 41, 31))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(660, 40, 61, 23))
        self.pushButton.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 120, 61, 23))
        self.pushButton_2.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 120, 61, 23))
        self.pushButton_3.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(610, 110, 101, 23))
        self.pushButton_4.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 681, 31))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 520, 241, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(510, 520, 241, 21))
        self.label_6.setObjectName("label_6")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 160, 771, 351))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "河众扫描"))
        self.label.setText(_translate("Form", "C:/"))
        self.label_2.setText(_translate("Form", "路径："))
        self.pushButton.setText(_translate("Form", "选择"))
        self.pushButton_2.setText(_translate("Form", "开始"))
        self.pushButton_3.setText(_translate("Form", "停止"))
        self.pushButton_4.setText(_translate("Form", "隔离所有"))
        self.label_4.setText(_translate("Form", "扫描中："))
        self.label_5.setText(_translate("Form", "发现病毒："))
        self.label_6.setText(_translate("Form", "已经扫描："))
