# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(712, 553)
        Form.setStyleSheet("background-color: #e0f7fa")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 121, 16))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 121, 16))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 110, 75, 23))
        self.pushButton.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 110, 75, 23))
        self.pushButton_2.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 140, 75, 23))
        self.pushButton_3.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 140, 75, 23))
        self.pushButton_5.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 151, 16))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 290, 75, 23))
        self.pushButton_7.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(270, 290, 75, 23))
        self.pushButton_8.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 151, 16))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(180, 260, 75, 23))
        self.pushButton_9.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(270, 260, 75, 23))
        self.pushButton_10.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 170, 151, 16))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(160, 170, 75, 23))
        self.pushButton_11.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(250, 170, 75, 23))
        self.pushButton_12.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 420, 671, 21))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(10, 390, 161, 16))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(190, 390, 75, 23))
        self.pushButton_13.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(270, 390, 75, 23))
        self.pushButton_14.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 80, 51, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 51, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 200, 141, 16))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(160, 200, 75, 23))
        self.pushButton_15.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(250, 200, 75, 23))
        self.pushButton_16.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 320, 161, 16))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 350, 161, 16))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setGeometry(QtCore.QRect(180, 320, 75, 23))
        self.pushButton_17.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Form)
        self.pushButton_18.setGeometry(QtCore.QRect(270, 320, 75, 23))
        self.pushButton_18.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(Form)
        self.pushButton_19.setGeometry(QtCore.QRect(270, 350, 75, 21))
        self.pushButton_19.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(Form)
        self.pushButton_20.setGeometry(QtCore.QRect(180, 350, 75, 23))
        self.pushButton_20.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 450, 671, 21))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(340, 116, 181, 20))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.pushButton_21 = QtWidgets.QPushButton(Form)
        self.pushButton_21.setGeometry(QtCore.QRect(340, 150, 111, 23))
        self.pushButton_21.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Form)
        self.pushButton_22.setGeometry(QtCore.QRect(340, 180, 111, 23))
        self.pushButton_22.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(340, 80, 51, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(10, 480, 671, 21))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(360, 260, 341, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(360, 290, 181, 20))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pushButton_23 = QtWidgets.QPushButton(Form)
        self.pushButton_23.setGeometry(QtCore.QRect(360, 320, 75, 23))
        self.pushButton_23.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(Form)
        self.pushButton_24.setGeometry(QtCore.QRect(450, 320, 75, 23))
        self.pushButton_24.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.pushButton_24.setObjectName("pushButton_24")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "河众设置"))
        self.label_2.setText(_translate("Form", "实时监控：开启"))
        self.label_4.setText(_translate("Form", "进程监控：开启"))
        self.pushButton.setText(_translate("Form", "开启"))
        self.pushButton_2.setText(_translate("Form", "关闭"))
        self.pushButton_3.setText(_translate("Form", "开启"))
        self.pushButton_5.setText(_translate("Form", "关闭"))
        self.label_6.setText(_translate("Form", "深度学习引擎：开启"))
        self.pushButton_7.setText(_translate("Form", "开启"))
        self.pushButton_8.setText(_translate("Form", "关闭"))
        self.label_7.setText(_translate("Form", "特征规则引擎：开启"))
        self.pushButton_9.setText(_translate("Form", "开启"))
        self.pushButton_10.setText(_translate("Form", "关闭"))
        self.label_8.setText(_translate("Form", "引导监控：开启"))
        self.pushButton_11.setText(_translate("Form", "开启"))
        self.pushButton_12.setText(_translate("Form", "关闭"))
        self.label_10.setText(_translate("Form", "注意：“扫描跳过大文件”会跳过文件体积大于50MB的文件！"))
        self.label_11.setText(_translate("Form", "扫描跳过大文件：关闭"))
        self.pushButton_13.setText(_translate("Form", "开启"))
        self.pushButton_14.setText(_translate("Form", "关闭"))
        self.label.setText(_translate("Form", "防护："))
        self.label_5.setText(_translate("Form", "扫描："))
        self.label_9.setText(_translate("Form", "注册表监控：开启"))
        self.pushButton_15.setText(_translate("Form", "开启"))
        self.pushButton_16.setText(_translate("Form", "关闭"))
        self.label_12.setText(_translate("Form", "云端扫描引擎：开启"))
        self.label_13.setText(_translate("Form", "PE启发式引擎：关闭"))
        self.pushButton_17.setText(_translate("Form", "开启"))
        self.pushButton_18.setText(_translate("Form", "关闭"))
        self.pushButton_19.setText(_translate("Form", "关闭"))
        self.pushButton_20.setText(_translate("Form", "开启"))
        self.label_14.setText(_translate("Form", "PE引擎仍在试验！"))
        self.label_15.setText(_translate("Form", "设置镜像源：河众大陆源"))
        self.pushButton_21.setText(_translate("Form", "设置为 河众大陆源"))
        self.pushButton_22.setText(_translate("Form", "设置为 河众台湾源"))
        self.label_16.setText(_translate("Form", "更新："))
        self.label_17.setText(_translate("Form", "镜像源设置说明：河众大陆源为最新源 河众台湾源每30分钟与大陆源同步一次"))
        self.label_18.setText(_translate("Form", "危险（启动这里的选项可能会导致系统崩溃！）："))
        self.label_19.setText(_translate("Form", "深度学习参与监控：关闭"))
        self.pushButton_23.setText(_translate("Form", "开启"))
        self.pushButton_24.setText(_translate("Form", "关闭"))
