# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 614)
        MainWindow.setStyleSheet("background-color: #e0f7fa")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.hub_chasha = QtWidgets.QPushButton(self.centralwidget)
        self.hub_chasha.setGeometry(QtCore.QRect(10, 130, 171, 71))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(24)
        self.hub_chasha.setFont(font)
        self.hub_chasha.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  \n"
"")
        self.hub_chasha.setObjectName("hub_chasha")
        self.hub_setting = QtWidgets.QPushButton(self.centralwidget)
        self.hub_setting.setGeometry(QtCore.QRect(10, 210, 171, 71))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(24)
        self.hub_setting.setFont(font)
        self.hub_setting.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.hub_setting.setObjectName("hub_setting")
        self.hub_setting_2 = QtWidgets.QPushButton(self.centralwidget)
        self.hub_setting_2.setGeometry(QtCore.QRect(10, 290, 171, 71))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(24)
        self.hub_setting_2.setFont(font)
        self.hub_setting_2.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.hub_setting_2.setObjectName("hub_setting_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 40, 131, 121))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 310, 161, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 350, 161, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 390, 181, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.hub_setting_4 = QtWidgets.QPushButton(self.centralwidget)
        self.hub_setting_4.setGeometry(QtCore.QRect(10, 510, 101, 51))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.hub_setting_4.setFont(font)
        self.hub_setting_4.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.hub_setting_4.setObjectName("hub_setting_4")
        self.hub_setting_5 = QtWidgets.QPushButton(self.centralwidget)
        self.hub_setting_5.setGeometry(QtCore.QRect(680, 530, 71, 41))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(12)
        self.hub_setting_5.setFont(font)
        self.hub_setting_5.setStyleSheet("QPushButton {  \n"
"    background-color: #e0f7fa;  \n"
"    border: none;\n"
"    color: black;\n"
"    border-radius: 10px;  \n"
"}\n"
"QPushButton:hover {  \n"
"    background-color: #b3e5fc;\n"
"}  \n"
"  \n"
"QPushButton:pressed {  \n"
"    background-color: #80deea;\n"
"}  ")
        self.hub_setting_5.setObjectName("hub_setting_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 170, 291, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(26)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 430, 181, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(200, 150, 31, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("./UI/lib/scan.png"))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(200, 230, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("./UI/lib/set.png"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 300, 31, 31))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("./UI/lib/do.png"))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(110, 520, 31, 31))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("./UI/lib/qu.png"))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "河众反病毒 6.0"))
        self.hub_chasha.setText(_translate("MainWindow", "扫描"))
        self.hub_setting.setText(_translate("MainWindow", "设置"))
        self.hub_setting_2.setText(_translate("MainWindow", "更新"))
        self.label_3.setText(_translate("MainWindow", "实时监控：开启"))
        self.label_4.setText(_translate("MainWindow", "进程监控：开启"))
        self.label_5.setText(_translate("MainWindow", "引导监控：开启"))
        self.hub_setting_4.setText(_translate("MainWindow", "隔离区"))
        self.hub_setting_5.setText(_translate("MainWindow", "关于河众"))
        self.label_6.setText(_translate("MainWindow", "未知"))
        self.label_7.setText(_translate("MainWindow", "注册表监控：开启"))
